# Generated by Django 3.2.25 on 2025-11-01 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_gmailtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GmailTransaction',
        ),
    ]
