# Generated by Django 3.2.25 on 2025-11-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20251101_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GmailCredential',
        ),
    ]
