# Generated by Django 3.2.25 on 2025-11-02 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_gmailemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmailtransaction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='description',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
