# Generated by Django 3.2.25 on 2025-11-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251102_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
