# Generated by Django 5.2.6 on 2025-09-08 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_address_userprofile_dob_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailcredential',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gmailcredential',
            name='token',
        ),
        migrations.AlterField(
            model_name='gmailcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_gmail_credential', to=settings.AUTH_USER_MODEL),
        ),
    ]
