# Generated by Django 3.2.25 on 2025-11-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='description',
            field=models.TextField(default='timezone'),
            preserve_default=False,
        ),
    ]
