# Generated by Django 3.2.25 on 2025-11-01 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_email_alter_userprofile_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailcredential',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='token',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='UserGoogleToken',
        ),
    ]
