# Generated by Django 3.2.25 on 2025-11-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20251102_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='category',
            field=models.CharField(default='timezone', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='transaction_type',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='currency',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
