# Generated by Django 3.2.25 on 2025-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20251102_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtransaction',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
