# Generated by Django 3.2.25 on 2025-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_gmailtransaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='GmailEmail',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
