# Generated by Django 3.2.25 on 2025-11-01 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_gmailtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailcredential',
            name='token',
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='access_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='refresh_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='scopes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='token_uri',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gmailcredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gmailcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_credential', to=settings.AUTH_USER_MODEL),
        ),
    ]
