# Generated by Django 3.2.25 on 2025-11-02 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20251102_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='message_id',
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='category',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='transaction_type',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='currency',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GmailEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
