# Generated by Django 3.2.25 on 2025-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20251101_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailcredential',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='currency',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
