# Generated by Django 3.2.25 on 2025-11-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20251102_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
