# Generated by Django 3.2.25 on 2025-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20251101_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtransaction',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='fraud_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
        ),
    ]
