# Generated by Django 3.2.25 on 2025-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20251102_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtransaction',
            name='gmail_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
