# Generated by Django 3.2.25 on 2025-11-03 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_gmailtransaction_gmail_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmailtransaction',
            old_name='message_id',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='gmail_link',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='snippet',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
