# Generated by Django 3.2.25 on 2025-11-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20251103_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='snippet',
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
