# Generated by Django 3.2.25 on 2025-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_gmailtransaction_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtransaction',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='currency',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='gmail_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
    ]
