# Generated by Django 3.2.25 on 2025-11-03 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20251103_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='is_fraud',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='snippet',
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='gmail_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='message_id',
            field=models.CharField(default='timezon.now', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='sender',
            field=models.CharField(default='timezon.now', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='subject',
            field=models.CharField(default='timezon.now', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='transaction_type',
            field=models.CharField(max_length=20),
        ),
    ]
