# Generated by Django 3.2.25 on 2025-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20251103_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailtransaction',
            name='category',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gmailtransaction',
            name='transaction_type',
            field=models.CharField(default='debit', max_length=20),
        ),
    ]
