# Generated by Django 3.2.25 on 2025-11-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_gmailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtransaction',
            name='fraud_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
