# Generated by Django 3.2.25 on 2025-11-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20251103_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmailtransaction',
            old_name='is_fraud',
            new_name='is_fraudulent',
        ),
        migrations.RemoveField(
            model_name='gmailtransaction',
            name='fraud_reason',
        ),
    ]
