# Generated by Django 3.2.25 on 2025-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20251103_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmailtransaction',
            old_name='is_fraudulent',
            new_name='is_fraud',
        ),
        migrations.AddField(
            model_name='gmailtransaction',
            name='fraud_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
