# Generated by Django 3.2.25 on 2025-11-03 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_fraudalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraudalert',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
