# Generated by Django 3.2.25 on 2025-11-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20251103_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtransaction',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
