# Generated by Django 3.2.25 on 2025-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_gmailtransaction_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='title',
            field=models.CharField(default='🚨 Suspicious Transaction Detected', max_length=255),
        ),
    ]
