# Generated by Django 5.0.6 on 2025-11-04 11:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction amount (in currency units).', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], help_text='Type of transaction: Credit (income) or Debit (expense).', max_length=10)),
                ('category', models.CharField(blank=True, help_text='Category like Food, Rent, Salary, etc.', max_length=50, null=True)),
                ('is_fraud', models.BooleanField(default=False, help_text='Flagged by fraud detection logic.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this transaction occurred.')),
                ('description', models.CharField(blank=True, help_text='Optional transaction note or description.', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
