# Generated by Django 3.2.25 on 2025-11-03 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('preview', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('prediction', models.BooleanField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
