# Generated by Django 4.2.24 on 2025-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='financial_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='monthly_savings_goal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='risk_tolerance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
    ]
