# Generated by Django 3.2.25 on 2025-11-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_fraudalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudAlert',
        ),
    ]
