# Generated by Django 4.2.24 on 2025-09-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_smartsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='debts',
            field=models.FloatField(default=0.0),
        ),
    ]
