# Generated by Django 4.2.24 on 2025-09-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_financialprofile_debts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprofile',
            name='debts',
        ),
    ]
