# Generated by Django 3.2.25 on 2025-11-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0006_gmailcredential'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialprofile',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='GmailCredential',
        ),
    ]
